CREATE TABLE "public"."customers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT "pk_customers" PRIMARY KEY ("id")
);

CREATE TABLE "public"."orders" (
    "id" bigint NOT NULL,
    "customer_id" bigint NOT NULL,
    CONSTRAINT "fk_orders_customer" FOREIGN KEY ("customer_id") REFERENCES "public"."customers" ("id") ON DELETE CASCADE
);

CREATE TABLE "public"."audit_alpha" (
    "id" bigint NOT NULL,
    "external_user_id" bigint,
    CONSTRAINT "fk_audit_external" FOREIGN KEY ("external_user_id") REFERENCES "public"."external_users" ("id")
);

CREATE TABLE "public"."audit_beta" (
    "id" bigint NOT NULL
);
