CREATE TABLE "public"."customers" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" varchar(255) NOT NULL,
    "display_name" varchar(100),
    CONSTRAINT "pk_customers" PRIMARY KEY ("id"),
    CONSTRAINT "uq_customers_email" UNIQUE ("email")
);
