using SqlScriptGen.Core;

namespace SqlScriptGen.Core.Tests;

public sealed class DocumentValidationAndOrderingTests
{
    [Fact] public void MissingInternalReferencedColumn_IsRejectedAtSourceConstraint() { var document = Document(Table("parent"), Child(new("fk_child_parent", ["parent_id"], "parent", ["missing"]))); var result = SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.PostgreSql); var error = Assert.Single(result.Errors, x => x.Path == "objects[1].constraints[0].referencedColumns[0]"); Assert.Contains("missing", error.Message); Assert.Contains("Table:parent", error.Message); Assert.Throws<SqlValidationException>(() => new SqlGenerator().Generate(document, DatabaseDialect.PostgreSql)); }
    [Fact] public void Identity_IsCaseInsensitiveAndStable() { var a = new DatabaseObjectIdentity(DatabaseObjectKind.Table, "Users", "Public"); var b = new DatabaseObjectIdentity(DatabaseObjectKind.Table, "users", "public"); Assert.Equal(a, b); Assert.Equal(a.GetHashCode(), b.GetHashCode()); }
    [Fact] public void QualifiedAndUnqualifiedTables_Differ() => Assert.NotEqual(new DatabaseObjectIdentity(DatabaseObjectKind.Table, "t"), new DatabaseObjectIdentity(DatabaseObjectKind.Table, "t", "public"));
    [Fact] public void DatabaseAndTableKinds_Differ() => Assert.NotEqual(new DatabaseObjectIdentity(DatabaseObjectKind.Database, "x"), new DatabaseObjectIdentity(DatabaseObjectKind.Table, "x"));
    [Fact] public void DuplicateObjects_AreRejected() => Invalid(Document(Table("Users"), Table("users")), "Duplicate object", "objects[1].name");
    [Fact] public void EmptyDocument_IsRejected() => Invalid(Document(), "At least one", "objects");
    [Fact] public void MixedDatabaseAndTables_AreRejected() => Invalid(Document(Table("t"), new DatabaseDefinition("db")), "cannot be mixed", "objects");
    [Fact] public void MissingExplicitDependency_IsRejected() { var t = Table("t") with { DependsOn = [Id("missing")] }; Invalid(Document(t), "does not exist", "objects[0].dependsOn[0]"); }
    [Fact] public void SelfDependency_IsRejected() { var t = Table("t") with { DependsOn = [Id("t")] }; Invalid(Document(t), "depend on itself", "objects[0].dependsOn[0]"); }
    [Fact] public void ExternalForeignKey_IsAllowed() { var t = Table("t", new ForeignKeyConstraint("fk", ["id"], "external", ["id"])); var document = Document(t); Assert.True(SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.PostgreSql).IsValid); Assert.Contains("REFERENCES \"external\" (\"id\")", new SqlGenerator().Generate(document, DatabaseDialect.PostgreSql).Sql); }
    [Fact] public void SelfReferencingForeignKey_DoesNotCreateDependencyCycle() { var t = TableColumns("t", null, "id", "parent_id") with { Constraints = [new ForeignKeyConstraint("fk", ["parent_id"], "t", ["id"])] }; Assert.True(SqlDefinitionDocumentValidator.Validate(Document(t), DatabaseDialect.PostgreSql).IsValid); }
    [Fact] public void SelfReferencingForeignKey_MissingColumnIsRejectedWithoutCycle() { var t = Table("t", new ForeignKeyConstraint("fk", ["id"], "t", ["missing"])); var result = SqlDefinitionDocumentValidator.Validate(Document(t), DatabaseDialect.PostgreSql); Assert.Contains(result.Errors, x => x.Path == "objects[0].constraints[0].referencedColumns[0]"); Assert.DoesNotContain(result.Errors, x => x.Message.Contains("cycle", StringComparison.OrdinalIgnoreCase)); }
    [Fact] public void InternalForeignKey_OrdersTargetFirst() { var child = Table("child", new ForeignKeyConstraint("fk", ["id"], "parent", ["id"])); Assert.Equal(["parent", "child"], DatabaseObjectOrderer.Order(Document(child, Table("parent"))).Select(x => x.Identity.Name)); }
    [Fact] public void ValidInternalForeignKey_GeneratesParentFirst() { var document = Document(Child(new("fk", ["parent_id"], "parent", ["id"])), Table("parent")); var result = SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.PostgreSql); Assert.True(result.IsValid); var sql = new SqlGenerator().Generate(document, DatabaseDialect.PostgreSql).Sql; Assert.True(sql.IndexOf("CREATE TABLE \"parent\"", StringComparison.Ordinal) < sql.IndexOf("CREATE TABLE \"child\"", StringComparison.Ordinal)); Assert.Contains("REFERENCES \"parent\" (\"id\")", sql); }
    [Fact] public void CompositeInternalForeignKey_ValidatesEachReferencedColumn() { var parent = TableColumns("parent", null, "tenant_id", "id"); var valid = Document(parent, Child(new("fk", ["tenant_id", "parent_id"], "parent", ["tenant_id", "id"]), "tenant_id", "parent_id")); Assert.True(SqlDefinitionDocumentValidator.Validate(valid, DatabaseDialect.PostgreSql).IsValid); var invalid = Document(parent, Child(new("fk", ["tenant_id", "parent_id"], "parent", ["tenant_id", "missing"]), "tenant_id", "parent_id")); var error = Assert.Single(SqlDefinitionDocumentValidator.Validate(invalid, DatabaseDialect.PostgreSql).Errors, x => x.Path.Contains("referencedColumns", StringComparison.Ordinal)); Assert.Equal("objects[1].constraints[0].referencedColumns[1]", error.Path); }
    [Theory, InlineData(DatabaseDialect.PostgreSql, "REFERENCES \"Parent\" (\"ID\")"), InlineData(DatabaseDialect.MySql, "REFERENCES `Parent` (`ID`)")]
    public void ExactMixedCaseInternalForeignKey_IsValidatedOrderedAndRendered(DatabaseDialect dialect, string expected) { var child = Child(new("fk", ["parent_id"], "Parent", ["ID"])); var parent = TableColumns("Parent", null, "ID"); var document = Document(child, parent); Assert.True(SqlDefinitionDocumentValidator.Validate(document, dialect).IsValid); Assert.Equal(["Parent", "child"], Names(DatabaseObjectOrderer.Order(document))); Assert.Contains(expected, new SqlGenerator().Generate(document, dialect).Sql); }
    [Theory, InlineData(DatabaseDialect.PostgreSql, "REFERENCES \"parent\" (\"ID\")"), InlineData(DatabaseDialect.MySql, "REFERENCES `parent` (`ID`)")]
    public void TableCaseMismatch_RemainsExternalAndPreservesDeclarationOrder(DatabaseDialect dialect, string expected) { var child = Child(new("fk", ["parent_id"], "parent", ["ID"])); var parent = TableColumns("Parent", null, "ID"); var document = Document(child, parent); Assert.True(SqlDefinitionDocumentValidator.Validate(document, dialect).IsValid); Assert.Equal(["child", "Parent"], Names(DatabaseObjectOrderer.Order(document))); var sql = new SqlGenerator().Generate(document, dialect).Sql; Assert.Contains(expected, sql); Assert.DoesNotContain(dialect == DatabaseDialect.PostgreSql ? "REFERENCES \"Parent\"" : "REFERENCES `Parent`", sql); }
    [Fact] public void ReferencedColumnCaseMismatch_IsRejectedAtIndexedPath() { var document = Document(TableColumns("Parent", null, "ID"), Child(new("fk", ["parent_id"], "Parent", ["id"]))); var error = Assert.Single(SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.PostgreSql).Errors, x => x.Path == "objects[1].constraints[0].referencedColumns[0]"); Assert.Contains("id", error.Message); Assert.Contains("Table:Parent", error.Message); Assert.Throws<SqlValidationException>(() => new SqlGenerator().Generate(document, DatabaseDialect.PostgreSql)); }
    [Theory, InlineData("audit", "Parent"), InlineData("Audit", "parent")]
    public void SchemaOrTableCaseMismatch_DoesNotResolveQualifiedTarget(string referencedSchema, string referencedTable) { var child = Child(new("fk", ["parent_id"], referencedTable, ["missing"], referencedSchema)) with { Schema = "Audit" }; var parent = TableColumns("Parent", "Audit", "ID"); var document = Document(child, parent); Assert.True(SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.PostgreSql).IsValid); Assert.Equal(["child", "Parent"], Names(DatabaseObjectOrderer.Order(document))); var sql = new SqlGenerator().Generate(document, DatabaseDialect.PostgreSql).Sql; Assert.Contains($"REFERENCES \"{referencedSchema}\".\"{referencedTable}\" (\"missing\")", sql); }
    [Fact] public void ExactQualifiedMixedCaseTarget_IsInternal() { var child = Child(new("fk", ["parent_id"], "Parent", ["ID"], "Audit")) with { Schema = "Audit" }; var parent = TableColumns("Parent", "Audit", "ID"); var document = Document(child, parent); Assert.True(SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.PostgreSql).IsValid); Assert.Equal(["Parent", "child"], Names(DatabaseObjectOrderer.Order(document))); Assert.Contains("REFERENCES \"Audit\".\"Parent\" (\"ID\")", new SqlGenerator().Generate(document, DatabaseDialect.PostgreSql).Sql); }
    [Fact] public void ExactQualifiedMixedCaseSelfReference_DoesNotCreateCycle() { var node = TableColumns("Node", "Audit", "ID", "ParentID") with { Constraints = [new ForeignKeyConstraint("fk", ["ParentID"], "Node", ["ID"], "Audit")] }; var document = Document(node); var result = SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.PostgreSql); Assert.True(result.IsValid); Assert.DoesNotContain(result.Errors, x => x.Message.Contains("cycle", StringComparison.OrdinalIgnoreCase)); Assert.Contains("REFERENCES \"Audit\".\"Node\" (\"ID\")", new SqlGenerator().Generate(document, DatabaseDialect.PostgreSql).Sql); var mismatch = node with { Constraints = [new ForeignKeyConstraint("fk", ["ParentID"], "node", ["ID"], "Audit")] }; Assert.True(SqlDefinitionDocumentValidator.Validate(Document(mismatch), DatabaseDialect.PostgreSql).IsValid); }
    [Fact] public void CompositeReferencedColumns_RequireExactCasePerIndex() { var parent = TableColumns("Parent", null, "TenantID", "ID"); var valid = Document(parent, Child(new("fk", ["tenant", "parent_id"], "Parent", ["TenantID", "ID"]), "tenant", "parent_id")); Assert.True(SqlDefinitionDocumentValidator.Validate(valid, DatabaseDialect.PostgreSql).IsValid); var invalid = Document(parent, Child(new("fk", ["tenant", "parent_id"], "Parent", ["tenantid", "ID"]), "tenant", "parent_id")); var error = Assert.Single(SqlDefinitionDocumentValidator.Validate(invalid, DatabaseDialect.PostgreSql).Errors, x => x.Path.Contains("referencedColumns", StringComparison.Ordinal)); Assert.Equal("objects[1].constraints[0].referencedColumns[0]", error.Path); }
    [Fact] public void ExplicitSchema_SelectsQualifiedTarget() { var publicParent = TableColumns("parent", "public", "public_id"); var auditParent = TableColumns("parent", "audit", "audit_id"); var validChild = Child(new("fk", ["parent_id"], "parent", ["audit_id"], "audit")) with { Schema = "public" }; Assert.True(SqlDefinitionDocumentValidator.Validate(Document(publicParent, auditParent, validChild), DatabaseDialect.PostgreSql).IsValid); var invalidChild = Child(new("fk", ["parent_id"], "parent", ["public_id"], "audit")) with { Schema = "public" }; var error = Assert.Single(SqlDefinitionDocumentValidator.Validate(Document(publicParent, auditParent, invalidChild), DatabaseDialect.PostgreSql).Errors, x => x.Path.Contains("referencedColumns", StringComparison.Ordinal)); Assert.Contains("Table:audit.parent", error.Message); }
    [Theory, InlineData(DatabaseDialect.PostgreSql, "REFERENCES \"audit\".\"parent\" (\"id\")"), InlineData(DatabaseDialect.MySql, "REFERENCES `audit`.`parent` (`id`)")]
    public void ExplicitSameSchemaReference_IsQualifiedAndOrdersParent(DatabaseDialect dialect, string expected) { var parent = TableColumns("parent", "audit", "id"); var child = Child(new("fk", ["parent_id"], "parent", ["id"], "audit")) with { Schema = "audit" }; var document = Document(child, parent); Assert.True(SqlDefinitionDocumentValidator.Validate(document, dialect).IsValid); var sql = new SqlGenerator().Generate(document, dialect).Sql; Assert.True(sql.IndexOf("parent", StringComparison.Ordinal) < sql.IndexOf("child", StringComparison.Ordinal)); Assert.Contains(expected, sql); }
    [Theory, InlineData(DatabaseDialect.PostgreSql, "REFERENCES \"parent\" (\"missing\")"), InlineData(DatabaseDialect.MySql, "REFERENCES `parent` (`missing`)")]
    public void OmittedSchema_DoesNotMatchQualifiedTarget(DatabaseDialect dialect, string expected) { var child = Child(new("fk", ["parent_id"], "parent", ["missing"])) with { Schema = "audit" }; var parent = TableColumns("parent", "audit", "id"); var document = Document(child, parent); var result = SqlDefinitionDocumentValidator.Validate(document, dialect); Assert.True(result.IsValid); Assert.Equal(["child", "parent"], Names(DatabaseObjectOrderer.Order(document))); Assert.Contains(expected, new SqlGenerator().Generate(document, dialect).Sql); }
    [Fact] public void UnqualifiedReference_MatchesOnlyUnqualifiedTargetRegardlessOfSourceSchema() { var qualified = TableColumns("parent", "audit", "other"); var unqualified = TableColumns("parent", null, "id"); var child = Child(new("fk", ["parent_id"], "parent", ["id"])) with { Schema = "audit" }; var document = Document(child, qualified, unqualified); Assert.True(SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.PostgreSql).IsValid); var ordered = DatabaseObjectOrderer.Order(document); Assert.Equal(["audit", null, "audit"], ordered.Select(x => x.Identity.Schema)); Assert.Equal(["parent", "parent", "child"], Names(ordered)); var invalid = Document(qualified, unqualified, Child(new("fk", ["parent_id"], "parent", ["missing"])) with { Schema = "audit" }); Assert.Contains(SqlDefinitionDocumentValidator.Validate(invalid, DatabaseDialect.PostgreSql).Errors, x => x.Path == "objects[2].constraints[0].referencedColumns[0]" && x.Message.Contains("Table:parent", StringComparison.Ordinal)); }
    [Fact] public void ExplicitDependency_OrdersQualifiedTableWithoutQualifyingForeignKey() { var parent = TableColumns("parent", "audit", "id"); var child = (Child(new("fk", ["parent_id"], "parent", ["missing"])) with { Schema = "audit", DependsOn = [new(DatabaseObjectKind.Table, "parent", "audit")] }); var document = Document(child, parent); Assert.True(SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.PostgreSql).IsValid); Assert.Equal(["parent", "child"], Names(DatabaseObjectOrderer.Order(document))); var sql = new SqlGenerator().Generate(document, DatabaseDialect.PostgreSql).Sql; Assert.Contains("REFERENCES \"parent\" (\"missing\")", sql); Assert.DoesNotContain("REFERENCES \"audit\".\"parent\"", sql); Assert.Null(Assert.IsType<ForeignKeyConstraint>(Assert.Single(child.Constraints!)).ReferencedSchema); }
    [Fact] public void QualifiedSelfReference_IsInternalButUnqualifiedIsNotInferred() { var explicitTable = TableColumns("node", "audit", "id", "parent_id") with { Constraints = [new ForeignKeyConstraint("fk", ["parent_id"], "node", ["id"], "audit")] }; Assert.True(SqlDefinitionDocumentValidator.Validate(Document(explicitTable), DatabaseDialect.PostgreSql).IsValid); Assert.Contains("REFERENCES \"audit\".\"node\"", new SqlGenerator().Generate(Document(explicitTable), DatabaseDialect.PostgreSql).Sql); var unqualified = explicitTable with { Constraints = [new ForeignKeyConstraint("fk", ["parent_id"], "node", ["missing"])] }; Assert.True(SqlDefinitionDocumentValidator.Validate(Document(unqualified), DatabaseDialect.PostgreSql).IsValid); Assert.Contains("REFERENCES \"node\" (\"missing\")", new SqlGenerator().Generate(Document(unqualified), DatabaseDialect.PostgreSql).Sql); }
    [Fact] public void StandaloneQualifiedSource_PreservesUnqualifiedForeignKey() { var table = Child(new("fk", ["parent_id"], "parent", ["id"])) with { Schema = "audit" }; var sql = new SqlGenerator().Generate(table, DatabaseDialect.PostgreSql).Sql; Assert.Contains("REFERENCES \"parent\" (\"id\")", sql); Assert.DoesNotContain("REFERENCES \"audit\".\"parent\"", sql); }
    [Fact] public void DuplicateInternalTarget_IsNotArbitrarilySelected() { var first = TableColumns("parent", null, "id"); var second = TableColumns("parent", null, "other"); var child = Child(new("fk", ["parent_id"], "parent", ["id"])); var result = SqlDefinitionDocumentValidator.Validate(Document(first, second, child), DatabaseDialect.PostgreSql); Assert.Contains(result.Errors, x => x.Message.Contains("Duplicate object", StringComparison.Ordinal)); Assert.DoesNotContain(result.Errors, x => x.Path.Contains("referencedColumns", StringComparison.Ordinal)); }
    [Fact] public void MalformedInternalTarget_DoesNotCrashCrossObjectValidation() { var parent = new TableDefinition("parent", null!); var child = Child(new("fk", ["parent_id"], "parent", ["id"])); var document = Document(parent, child); var result = SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.PostgreSql); Assert.Contains(result.Errors, x => x.Path == "objects[0].columns"); Assert.Throws<SqlValidationException>(() => new SqlGenerator().Generate(document, DatabaseDialect.PostgreSql)); }
    [Fact] public void SimpleChain_IsOrdered() { var c = Depends(Table("c"), "b"); var b = Depends(Table("b"), "a"); Assert.Equal(["a", "b", "c"], Names(DatabaseObjectOrderer.Order(Document(c, b, Table("a"))))); }
    [Fact] public void Diamond_IsOrderedStably() { var d = Table("d") with { DependsOn = [Id("b"), Id("c")] }; var b = Depends(Table("b"), "a"); var c = Depends(Table("c"), "a"); Assert.Equal(["a", "c", "b", "d"], Names(DatabaseObjectOrderer.Order(Document(d, c, b, Table("a"))))); }
    [Fact] public void DisconnectedObjects_KeepDeclarationTies() => Assert.Equal(["z", "a", "m"], Names(DatabaseObjectOrderer.Order(Document(Table("z"), Table("a"), Table("m")))));
    [Fact] public void DuplicateEdges_DoNotChangeOrder() { var b = Table("b") with { DependsOn = [Id("a"), Id("A")] }; Assert.Equal(["a", "b"], Names(DatabaseObjectOrderer.Order(Document(b, Table("a"))))); }
    [Fact] public void MultiNodeCycle_IsRejectedWithIdentities() { var a = Depends(Table("a"), "b"); var b = Depends(Table("b"), "a"); var result = SqlDefinitionDocumentValidator.Validate(Document(a, b), DatabaseDialect.PostgreSql); Assert.Contains(result.Errors, x => x.Message.Contains("Table:a") && x.Message.Contains("Table:b")); }
    [Fact] public void CycleDiagnostic_ExcludesBlockedNonCycleObjects() { var a = Depends(Table("a"), "b"); var b = Depends(Table("b"), "a"); var c = Depends(Table("c"), "a"); var error = Assert.Single(SqlDefinitionDocumentValidator.Validate(Document(a, b, c), DatabaseDialect.PostgreSql).Errors, x => x.Message.Contains("cycle", StringComparison.OrdinalIgnoreCase)); Assert.DoesNotContain("Table:c", error.Message); }
    [Fact] public void Ordering_IsRepeatableAndDoesNotMutateInput() { IDatabaseObject[] input = [Depends(Table("b"), "a"), Table("a"), Table("c")]; var document = Document(input); var first = Names(DatabaseObjectOrderer.Order(document)); var second = Names(DatabaseObjectOrderer.Order(document)); Assert.Equal(first, second); Assert.Equal(["b", "a", "c"], input.Select(x => x.Identity.Name)); }
    [Fact] public void MultipleErrors_AreCollectedWithStablePaths() { var bad = new TableDefinition("bad-name", [new("bad-col", new("missing"))]) with { DependsOn = [Id("absent")] }; var result = SqlDefinitionDocumentValidator.Validate(Document(bad), DatabaseDialect.MySql); Assert.True(result.Errors.Count >= 3); Assert.All(result.Errors, x => Assert.StartsWith("objects", x.Path)); }
    [Fact] public void MySqlCapabilityRejectsSetDefault() { var fk = new ForeignKeyConstraint("fk", ["id"], "external", ["id"], OnDelete: ReferentialAction.SetDefault); Invalid(Document(Table("t", fk)), "referential action", "objects[0].constraints"); }
    [Fact] public void ExistingConstructorsAndOverloads_RemainUsable() { var table = new TableDefinition("t", [new("id", new("int"))]); var database = new DatabaseDefinition("db"); var generator = new SqlGenerator(); Assert.Contains("CREATE TABLE", generator.Generate(table, DatabaseDialect.PostgreSql).Sql); Assert.Contains("CREATE DATABASE", generator.Generate(database, DatabaseDialect.PostgreSql).Sql); }
    private static SqlDefinitionDocument Document(params IDatabaseObject[] objects) => new(1, objects);
    private static TableDefinition Table(string name, params TableConstraint[] constraints) => new(name, [new("id", new("int"))], constraints);
    private static TableDefinition TableColumns(string name, string? schema, params string[] columns) => new(name, columns.Select(column => new ColumnDefinition(column, new("int"))).ToArray(), Schema: schema);
    private static TableDefinition Child(ForeignKeyConstraint foreignKey, params string[] columns) => new("child", (columns.Length == 0 ? ["parent_id"] : columns).Select(column => new ColumnDefinition(column, new("int"))).ToArray(), [foreignKey]);
    private static TableDefinition Depends(TableDefinition table, string name) => table with { DependsOn = [Id(name)] };
    private static DatabaseObjectIdentity Id(string name) => new(DatabaseObjectKind.Table, name);
    private static string[] Names(IReadOnlyList<IDatabaseObject> objects) => objects.Select(x => x.Identity.Name).ToArray();
    private static void Invalid(SqlDefinitionDocument document, string message, string path) { var result = SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.MySql); Assert.Contains(result.Errors, x => x.Path.StartsWith(path, StringComparison.Ordinal) && x.Message.Contains(message, StringComparison.OrdinalIgnoreCase)); }
}
