using System.Text.Json;
using SqlScriptGen.Core;

namespace SqlScriptGen.Core.Tests;

public sealed class DocumentSerializationTests
{
    [Theory, MemberData(nameof(InvalidNullStructures))] public void CanonicalNullStructure_IsJsonError(string json, string path) { var ex = Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read(json)); Assert.Contains(path, ex.Message); }
    [Fact] public void OptionalNullMembers_RemainAccepted() { const string json = "{\"formatVersion\":1,\"objects\":[{\"kind\":\"table\",\"name\":\"customers\",\"schema\":null,\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"},\"default\":null}],\"constraints\":null,\"dependsOn\":[]}]}"; var table = Assert.IsType<TableDefinition>(Assert.Single(SqlDefinitionDocumentJson.Read(json).Objects)); Assert.Null(table.Constraints); Assert.Null(table.Schema); }
    [Fact] public void TableKindAfterProperties_IsAccepted() { var table = Assert.IsType<TableDefinition>(Assert.Single(SqlDefinitionDocumentJson.Read("{\"formatVersion\":1,\"objects\":[{\"name\":\"customers\",\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}],\"kind\":\"table\"}]}").Objects)); Assert.Equal("customers", table.Name); Assert.Equal("id", Assert.Single(table.Columns).Name); }
    [Fact] public void DatabaseKindAfterName_IsAccepted() { var database = Assert.IsType<DatabaseDefinition>(Assert.Single(SqlDefinitionDocumentJson.Read("{\"formatVersion\":1,\"objects\":[{\"name\":\"application\",\"kind\":\"database\"}]}").Objects)); Assert.Equal("application", database.Name); }
    [Fact] public void PrimaryKeyKindAfterProperties_IsAccepted() { var table = Assert.IsType<TableDefinition>(Assert.Single(SqlDefinitionDocumentJson.Read(ConstraintDocument("{\"name\":\"pk_customers\",\"columns\":[\"id\"],\"kind\":\"primaryKey\"}")).Objects)); Assert.IsType<PrimaryKeyConstraint>(Assert.Single(table.Constraints!)); }
    [Fact] public void UniqueKindAfterProperties_IsAccepted() { var table = Assert.IsType<TableDefinition>(Assert.Single(SqlDefinitionDocumentJson.Read(ConstraintDocument("{\"name\":\"uq_customers\",\"columns\":[\"id\"],\"kind\":\"unique\"}")).Objects)); Assert.IsType<UniqueConstraint>(Assert.Single(table.Constraints!)); }
    [Fact] public void CheckKindAfterProperties_IsAccepted() { var table = Assert.IsType<TableDefinition>(Assert.Single(SqlDefinitionDocumentJson.Read(ConstraintDocument("{\"name\":\"ck_customers\",\"expression\":{\"value\":\"id > 0\"},\"kind\":\"check\"}")).Objects)); Assert.IsType<CheckConstraint>(Assert.Single(table.Constraints!)); }
    [Fact] public void ForeignKeyKindInMiddle_IsAccepted() { var table = Assert.IsType<TableDefinition>(Assert.Single(SqlDefinitionDocumentJson.Read(ConstraintDocument("{\"name\":\"fk_parent\",\"columns\":[\"id\"],\"kind\":\"foreignKey\",\"referencedTable\":\"parent\",\"referencedColumns\":[\"id\"],\"onDelete\":\"cascade\"}")).Objects)); var foreignKey = Assert.IsType<ForeignKeyConstraint>(Assert.Single(table.Constraints!)); Assert.Equal(ReferentialAction.Cascade, foreignKey.OnDelete); }
    [Fact] public void NestedMixedPropertyOrdering_DeserializesAndValidates() { const string json = "{\"formatVersion\":1,\"objects\":[{\"name\":\"parent\",\"schema\":\"public\",\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}],\"kind\":\"table\"},{\"name\":\"child\",\"schema\":\"public\",\"dependsOn\":[{\"name\":\"parent\",\"schema\":\"public\",\"kind\":\"table\"}],\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}],\"constraints\":[{\"name\":\"pk_child\",\"columns\":[\"id\"],\"kind\":\"primaryKey\"}],\"kind\":\"table\"}]}"; var document = SqlDefinitionDocumentJson.Read(json); Assert.True(SqlDefinitionDocumentValidator.Validate(document, DatabaseDialect.PostgreSql).IsValid); var canonical = SqlDefinitionDocumentJson.Serialize(document); Assert.Contains("{\n      \"kind\": \"table\",", canonical); Assert.Equal(canonical, SqlDefinitionDocumentJson.Serialize(SqlDefinitionDocumentJson.Read(canonical))); }
    [Fact] public void MissingObjectKind_IsJsonError() { var ex = Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read("{\"formatVersion\":1,\"objects\":[{\"name\":\"application\"}]}")); Assert.Contains("objects[0].kind", ex.Message); }
    [Fact] public void MissingTableKind_IsNotInferredFromColumns() { var ex = Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read("{\"formatVersion\":1,\"objects\":[{\"name\":\"customers\",\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}]}]}")); Assert.Contains("objects[0].kind", ex.Message); }
    [Fact] public void MissingConstraintKind_IsJsonError() { var ex = Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read(ConstraintDocument("{\"name\":\"pk_customers\",\"columns\":[\"id\"]}"))); Assert.Contains("objects[0].constraints[0].kind", ex.Message); }
    [Fact] public void MissingSecondObjectKind_ReportsCorrectIndex() { var ex = Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read("{\"formatVersion\":1,\"objects\":[{\"kind\":\"database\",\"name\":\"first\"},{\"name\":\"second\"}]}")); Assert.Contains("objects[1].kind", ex.Message); }
    [Fact] public void MissingLaterConstraintKind_ReportsCorrectIndex() { var ex = Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read("{\"formatVersion\":1,\"objects\":[{\"kind\":\"table\",\"name\":\"customers\",\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}],\"constraints\":[{\"kind\":\"primaryKey\",\"name\":\"pk_customers\",\"columns\":[\"id\"]},{\"name\":\"uq_customers\",\"columns\":[\"id\"]}]}]}")); Assert.Contains("objects[0].constraints[1].kind", ex.Message); }
    [Fact] public void DiscriminatorPropertyNames_AreCaseInsensitive() { var table = Assert.IsType<TableDefinition>(Assert.Single(SqlDefinitionDocumentJson.Read("{\"formatVersion\":1,\"objects\":[{\"KIND\":\"table\",\"name\":\"customers\",\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}],\"constraints\":[{\"KIND\":\"primaryKey\",\"name\":\"pk_customers\",\"columns\":[\"id\"]}]}]}").Objects)); Assert.IsType<PrimaryKeyConstraint>(Assert.Single(table.Constraints!)); }
    [Fact] public void UnknownConstraintKind_IsRejected() => Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read(ConstraintDocument("{\"name\":\"mystery\",\"columns\":[\"id\"],\"kind\":\"index\"}")));
    [Fact] public void MissingDependencyKind_IsRejectedEvenWhenTargetExists() { var ex = Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read(DependencyDocument("{\"name\":\"parent\"}"))); Assert.Contains("dependsOn[0]", ex.Path ?? string.Empty); }
    [Fact] public void MissingDependencyName_IsRejected() { var ex = Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read(DependencyDocument("{\"kind\":\"table\"}"))); Assert.Contains("dependsOn[0]", ex.Path ?? string.Empty); }
    [Fact] public void ValidDependency_DeserializesRequiredIdentity() { var document = SqlDefinitionDocumentJson.Read(DependencyDocument("{\"kind\":\"table\",\"name\":\"parent\"}")); var dependency = Assert.Single(document.Objects[1].DependsOn!); Assert.Equal(DatabaseObjectKind.Table, dependency.Kind); Assert.Equal("parent", dependency.Name); }
    [Fact] public void UnknownDependencyKind_IsRejected() => Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read(DependencyDocument("{\"kind\":\"view\",\"name\":\"parent\"}")));
    [Fact] public void CanonicalDocument_RoundTrips() { var value = Document(Table("a"), new DatabaseDefinition("db")); var roundTrip = SqlDefinitionDocumentJson.Read(SqlDefinitionDocumentJson.Serialize(value)); Assert.Collection(roundTrip.Objects, x => Assert.IsType<TableDefinition>(x), x => Assert.IsType<DatabaseDefinition>(x)); }
    [Fact] public void LegacyTable_IsAdapted() { var value = SqlDefinitionDocumentJson.Read("{\"name\":\"legacy\",\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}]}"); Assert.Equal(SqlDefinitionDocument.CurrentFormatVersion, value.FormatVersion); Assert.Equal("legacy", Assert.IsType<TableDefinition>(Assert.Single(value.Objects)).Name); }
    [Fact] public void LegacySerialization_DoesNotGainDocumentMetadata() => Assert.DoesNotContain("DependsOn", DefinitionJson.Serialize(Table("legacy")));
    [Fact] public void CanonicalSerialization_EmitsEnvelopeOnly() { var json = SqlDefinitionDocumentJson.Serialize(Document(Table("a"))); Assert.StartsWith("{\n  \"formatVersion\": 1,\n  \"objects\": [", json); Assert.Contains("\"kind\": \"table\"", json); Assert.EndsWith("\n", json); Assert.DoesNotContain("\r", json); }
    [Fact] public void UnknownFormatVersion_FailsClearly() { var ex = Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read("{\"formatVersion\":2,\"objects\":[]}")); Assert.Contains("formatVersion", ex.Message); Assert.Contains("unsupported", ex.Message); }
    [Fact] public void MissingFormatVersion_FailsClearly() { var ex = Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read("{\"objects\":[]}")); Assert.Contains("formatVersion", ex.Message); }
    [Fact] public void UnknownObjectKind_Fails() { var ex = Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read("{\"formatVersion\":1,\"objects\":[{\"kind\":\"view\",\"name\":\"v\"}]}")); Assert.Contains("discriminator", ex.Message, StringComparison.OrdinalIgnoreCase); }
    [Fact] public void UnknownMember_Fails() => Assert.Throws<JsonException>(() => SqlDefinitionDocumentJson.Read("{\"formatVersion\":1,\"objects\":[{\"kind\":\"database\",\"name\":\"db\",\"mystery\":true}]}"));
    [Fact] public void PropertyNames_AreCaseInsensitive() { var value = SqlDefinitionDocumentJson.Read("{\"FORMATVERSION\":1,\"OBJECTS\":[{\"kind\":\"database\",\"NAME\":\"db\"}]}"); Assert.Equal("db", Assert.IsType<DatabaseDefinition>(Assert.Single(value.Objects)).Name); }
    [Fact] public void ObjectDeclarationOrder_IsPreserved() { var value = SqlDefinitionDocumentJson.Read(SqlDefinitionDocumentJson.Serialize(Document(Table("z"), Table("a")))); Assert.Equal(["z", "a"], value.Objects.Select(x => x.Identity.Name)); }
    [Fact] public void ConstraintPolymorphism_IsPreserved() { var table = new TableDefinition("t", [new("id", new("int"))], [new PrimaryKeyConstraint("pk", ["id"])]); var value = SqlDefinitionDocumentJson.Read(SqlDefinitionDocumentJson.Serialize(Document(table))); Assert.IsType<PrimaryKeyConstraint>(Assert.Single(Assert.IsType<TableDefinition>(Assert.Single(value.Objects)).Constraints!)); }
    [Fact] public void ExplicitDependencies_RoundTrip() { var table = Table("b") with { DependsOn = [new(DatabaseObjectKind.Table, "a", "public")] }; var roundTrip = SqlDefinitionDocumentJson.Read(SqlDefinitionDocumentJson.Serialize(Document(table))); Assert.Equal(new DatabaseObjectIdentity(DatabaseObjectKind.Table, "A", "PUBLIC"), Assert.Single(roundTrip.Objects[0].DependsOn!)); }
    [Fact] public void UnsupportedVersion_CannotBeSerialized() => Assert.Throws<ArgumentException>(() => SqlDefinitionDocumentJson.Serialize(new(2, [Table("a")])));
    private static SqlDefinitionDocument Document(params IDatabaseObject[] objects) => new(1, objects);
    private static TableDefinition Table(string name) => new(name, [new("id", new("int"))]);
    private static string DependencyDocument(string dependency) => "{\"formatVersion\":1,\"objects\":[{\"kind\":\"table\",\"name\":\"parent\",\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}]},{\"kind\":\"table\",\"name\":\"child\",\"dependsOn\":[DEPENDENCY],\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}]}]}".Replace("DEPENDENCY", dependency, StringComparison.Ordinal);
    private static string ConstraintDocument(string constraint) => "{\"formatVersion\":1,\"objects\":[{\"kind\":\"table\",\"name\":\"customers\",\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}],\"constraints\":[CONSTRAINT]}]}".Replace("CONSTRAINT", constraint, StringComparison.Ordinal);
    public static IEnumerable<object[]> InvalidNullStructures()
    {
        yield return ["{\"formatVersion\":1,\"objects\":[null]}", "objects[0]"];
        yield return ["{\"formatVersion\":1,\"objects\":[{\"kind\":\"database\",\"name\":null}]}", "objects[0].name"];
        yield return ["{\"formatVersion\":1,\"objects\":[{\"kind\":\"table\",\"name\":null,\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}]}]}", "objects[0].name"];
        yield return [CanonicalTable("\"columns\":null"), "objects[0].columns"];
        yield return [CanonicalTable("\"columns\":[null]"), "objects[0].columns[0]"];
        yield return [CanonicalTable("\"columns\":[{\"name\":null,\"type\":{\"name\":\"int\"}}]"), "objects[0].columns[0].name"];
        yield return [CanonicalTable("\"columns\":[{\"name\":\"id\",\"type\":null}]"), "objects[0].columns[0].type"];
        yield return [CanonicalTable("\"columns\":[{\"name\":\"id\",\"type\":{\"name\":null}}]"), "objects[0].columns[0].type.name"];
        yield return [CanonicalTable(ValidColumns + ",\"constraints\":[null]"), "objects[0].constraints[0]"];
        yield return [CanonicalTable(ValidColumns + ",\"constraints\":[{\"kind\":\"primaryKey\",\"name\":\"pk\",\"columns\":null}]"), "objects[0].constraints[0].columns"];
        yield return [CanonicalTable(ValidColumns + ",\"constraints\":[{\"kind\":\"primaryKey\",\"name\":\"pk\",\"columns\":[null]}]"), "objects[0].constraints[0].columns[0]"];
        yield return [CanonicalTable(ValidColumns + ",\"constraints\":[{\"kind\":\"unique\",\"name\":\"uq\",\"columns\":[null]}]"), "objects[0].constraints[0].columns[0]"];
        yield return [CanonicalTable(ValidColumns + ",\"constraints\":[{\"kind\":\"check\",\"name\":\"ck\",\"expression\":null}]"), "objects[0].constraints[0].expression"];
        yield return [CanonicalTable(ValidColumns + ",\"constraints\":[{\"kind\":\"check\",\"name\":\"ck\",\"expression\":{\"value\":null}}]"), "objects[0].constraints[0].expression.value"];
        yield return [CanonicalTable(ValidColumns + ",\"constraints\":[{\"kind\":\"foreignKey\",\"name\":\"fk\",\"columns\":null,\"referencedTable\":\"parent\",\"referencedColumns\":[\"id\"]}]"), "objects[0].constraints[0].columns"];
        yield return [CanonicalTable(ValidColumns + ",\"constraints\":[{\"kind\":\"foreignKey\",\"name\":\"fk\",\"columns\":[null],\"referencedTable\":\"parent\",\"referencedColumns\":[\"id\"]}]"), "objects[0].constraints[0].columns[0]"];
        yield return [CanonicalTable(ValidColumns + ",\"constraints\":[{\"kind\":\"foreignKey\",\"name\":\"fk\",\"columns\":[\"id\"],\"referencedTable\":null,\"referencedColumns\":[\"id\"]}]"), "objects[0].constraints[0].referencedTable"];
        yield return [CanonicalTable(ValidColumns + ",\"constraints\":[{\"kind\":\"foreignKey\",\"name\":\"fk\",\"columns\":[\"id\"],\"referencedTable\":\"parent\",\"referencedColumns\":null}]"), "objects[0].constraints[0].referencedColumns"];
        yield return [CanonicalTable(ValidColumns + ",\"constraints\":[{\"kind\":\"foreignKey\",\"name\":\"fk\",\"columns\":[\"id\"],\"referencedTable\":\"parent\",\"referencedColumns\":[null]}]"), "objects[0].constraints[0].referencedColumns[0]"];
        yield return [CanonicalTable(ValidColumns + ",\"dependsOn\":[null]"), "objects[0].dependsOn[0]"];
        yield return [CanonicalTable(ValidColumns + ",\"dependsOn\":[{\"kind\":null,\"name\":\"parent\"}]"), "objects[0].dependsOn[0].kind"];
        yield return [CanonicalTable(ValidColumns + ",\"dependsOn\":[{\"kind\":\"table\",\"name\":null}]"), "objects[0].dependsOn[0].name"];
    }
    private const string ValidColumns = "\"columns\":[{\"name\":\"id\",\"type\":{\"name\":\"int\"}}]";
    private static string CanonicalTable(string members) => $"{{\"formatVersion\":1,\"objects\":[{{\"kind\":\"table\",\"name\":\"customers\",{members}}}]}}";
}
