using SqlScriptGen.Core;

namespace SqlScriptGen.Core.Tests;

public sealed class GeneratorTests
{
    private readonly SqlGenerator generator = new();
    [Fact] public void PostgreSql_BasicTable_IsExact() => Assert.Equal("CREATE TABLE \"items\" (\n    \"id\" bigint NOT NULL\n);\n", Generate(DatabaseDialect.PostgreSql, new("items", [new("id", new("bigint"), false)])));
    [Fact] public void MySql_BasicTable_IsExact() => Assert.Equal("CREATE TABLE `items` (\n    `id` BIGINT NOT NULL\n);\n", Generate(DatabaseDialect.MySql, new("items", [new("id", new("bigint"), false)])));
    [Theory, InlineData(DatabaseDialect.PostgreSql, '"'), InlineData(DatabaseDialect.MySql, '`')]
    public void Columns_PreserveOrder(DatabaseDialect dialect, char q) { var sql = Generate(dialect, new("t", [new("z", new("int")), new("a", new("int"))])); Assert.True(sql.IndexOf($"{q}z{q}", StringComparison.Ordinal) < sql.IndexOf($"{q}a{q}", StringComparison.Ordinal)); }
    [Fact] public void PostgreSql_RendersSchemaAndIdentity() => Assert.Contains("CREATE TABLE \"public\".\"order\" (\n    \"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL", Generate(DatabaseDialect.PostgreSql, new("order", [new("id", new("bigint"), false, Identity: true)], Schema: "public")));
    [Fact] public void MySql_RendersAutoIncrement() => Assert.Contains("`id` BIGINT AUTO_INCREMENT NOT NULL", Generate(DatabaseDialect.MySql, new("t", [new("id", new("bigint"), false, Identity: true)])));
    [Fact] public void PrimaryKey_Renders() => Assert.Contains("CONSTRAINT \"pk_t\" PRIMARY KEY (\"id\")", Generate(DatabaseDialect.PostgreSql, TableWith(new PrimaryKeyConstraint("pk_t", ["id"]))));
    [Fact] public void CompositePrimaryKey_Renders() => Assert.Contains("PRIMARY KEY (`id`, `tenant`)", Generate(DatabaseDialect.MySql, new("t", [new("id", new("int")), new("tenant", new("int"))], [new PrimaryKeyConstraint("pk_t", ["id", "tenant"])])));
    [Fact] public void Unique_Renders() => Assert.Contains("UNIQUE (\"id\")", Generate(DatabaseDialect.PostgreSql, TableWith(new UniqueConstraint("uq_t_id", ["id"]))));
    [Fact] public void Check_Renders() => Assert.Contains("CHECK (id > 0)", Generate(DatabaseDialect.PostgreSql, TableWith(new CheckConstraint("ck_t", new("id > 0")))));
    [Fact] public void ForeignKey_RendersWithoutExtraParentheses() => Assert.Contains("REFERENCES \"parent\" (\"id\")", Generate(DatabaseDialect.PostgreSql, TableWith(new ForeignKeyConstraint("fk_t", ["id"], "parent", ["id"]))));
    [Fact] public void ReferentialActions_Render() => Assert.Contains("ON DELETE CASCADE ON UPDATE RESTRICT", Generate(DatabaseDialect.MySql, TableWith(new ForeignKeyConstraint("fk_t", ["id"], "p", ["id"], OnDelete: ReferentialAction.Cascade, OnUpdate: ReferentialAction.Restrict))));
    [Fact] public void DefaultsAndNullability_Render() => Assert.Contains("\"created\" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL", Generate(DatabaseDialect.PostgreSql, new("t", [new("created", new("timestamp"), false, new("CURRENT_TIMESTAMP"))])));
    [Fact] public void Length_Renders() => Assert.Contains("varchar(255)", Generate(DatabaseDialect.PostgreSql, new("t", [new("name", new("varchar", 255))])));
    [Fact] public void Decimal_Renders() => Assert.Contains("DECIMAL(12,2)", Generate(DatabaseDialect.MySql, new("t", [new("price", new("decimal", Precision: 12, Scale: 2))])));
    [Theory, InlineData(DatabaseDialect.PostgreSql, "CREATE DATABASE \"sample\";\n"), InlineData(DatabaseDialect.MySql, "CREATE DATABASE `sample`;\n")]
    public void CreateDatabase_IsExact(DatabaseDialect dialect, string expected) => Assert.Equal(expected, generator.Generate(new DatabaseDefinition("sample"), dialect).Sql);
    [Fact] public void UsesLfLineEndings() { var sql = Generate(DatabaseDialect.PostgreSql, TableWith()); Assert.DoesNotContain("\r", sql); Assert.EndsWith(";\n", sql); }
    private string Generate(DatabaseDialect d, TableDefinition t) => generator.Generate(t, d).Sql;
    private static TableDefinition TableWith(params TableConstraint[] constraints) => new("t", [new("id", new("int"))], constraints);
}
